GifBolt.Native: GifBolt::GifDecoder Class Reference
GifBolt::GifDecoder Class Reference
Decodes GIF images from files or URLs.
#include <GifDecoder.h>
Public Member Functions
void SetMinFrameDelayMs (uint32_t minDelayMs)
Définit le délai minimal appliqué à chaque frame GIF (en ms).
uint32_t GetMinFrameDelayMs () const
Obtient le délai minimal appliqué à chaque frame GIF (en ms).
void SetMaxCachedFrames (uint32_t maxFrames)
Sets the maximum number of frames to cache in memory.
uint32_t GetMaxCachedFrames () const
Gets the maximum number of frames cached in memory.
GifDecoder ()
Initializes a new instance of the GifDecoder class.
~GifDecoder ()
Destroys the GifDecoder and releases associated resources.
bool LoadFromFile (const std::string &filePath)
Loads a GIF image from a file path.
bool LoadFromMemory (const uint8_t *data, size_t length)
Loads a GIF image from an in-memory buffer.
bool LoadFromUrl (const std::string &url)
Loads a GIF image from a URL.
uint32_t GetFrameCount () const
Gets the total number of frames in the GIF.
const GifFrame & GetFrame (uint32_t index) const
Gets the frame data at the specified index.
uint32_t GetWidth () const
Gets the width of the GIF image.
uint32_t GetHeight () const
Gets the height of the GIF image.
bool IsLooping () const
Determines whether the GIF loops indefinitely.
uint32_t GetBackgroundColor () const
Gets the background color of the GIF.
const uint8_t * GetFramePixelsBGRA32Premultiplied (uint32_t index)
Gets BGRA pixel data with premultiplied alpha for the specified frame.
const uint8_t * GetFramePixelsBGRA32PremultipliedScaled (uint32_t index, uint32_t targetWidth, uint32_t targetHeight, uint32_t &outWidth, uint32_t &outHeight, ScalingFilter filter=ScalingFilter::Bilinear)
Gets BGRA pixel data with premultiplied alpha for the specified frame, scaled to target dimensions.
void StartPrefetching (uint32_t startFrame)
Starts background prefetching of frames ahead of the current playback position.
void StopPrefetching ()
Stops background prefetching and joins the prefetch thread.
void SetCurrentFrame (uint32_t currentFrame)
Updates the current playback position for prefetch lookahead.
void ResetCanvas ()
Resets the canvas composition state for looping.
Detailed Description
Decodes GIF images from files or URLs.
Provides functionality to load and decode GIF images, with support for frame iteration, looping detection, and pixel data access.
Definition at line 46 of file GifDecoder.h.
Member Function Documentation
GetBackgroundColor()
uint32_t GifBolt::GifDecoder::GetBackgroundColor () const
Gets the background color of the GIF.
Returns
The background color as RGBA32 (0xAABBGGRR).
Definition at line 739 of file GifDecoder.cpp.
Referenced by gb_decoder_get_background_color().
GetFrame()
const GifFrame & GifBolt::GifDecoder::GetFrame (uint32_t index) const
Gets the frame data at the specified index.
Parameters
index The zero-based index of the frame.
Returns
A reference to the GifFrame at the specified index.
Exceptions
std::out_of_range if index >= GetFrameCount().
Definition at line 714 of file GifDecoder.cpp.
GetFrameCount()
uint32_t GifBolt::GifDecoder::GetFrameCount () const
Gets the total number of frames in the GIF.
Returns
The number of frames, or 0 if no GIF is loaded.
Definition at line 707 of file GifDecoder.cpp.
GetFramePixelsBGRA32Premultiplied()
const uint8_t * GifBolt::GifDecoder::GetFramePixelsBGRA32Premultiplied (uint32_t index)
Gets BGRA pixel data with premultiplied alpha for the specified frame.
Parameters
index The zero-based index of the frame.
Returns
A pointer to BGRA32 premultiplied pixel data, or nullptr on error. The data is cached internally and valid until the next call to this function.
Definition at line 767 of file GifDecoder.cpp.
References GifBolt::GifFrame::pixels.
Referenced by gb_decoder_get_frame_pixels_bgra32_premultiplied(), and GetFramePixelsBGRA32PremultipliedScaled().
GetFramePixelsBGRA32PremultipliedScaled()
const uint8_t * GifBolt::GifDecoder::GetFramePixelsBGRA32PremultipliedScaled (uint32_t index, uint32_t targetWidth, uint32_t targetHeight, uint32_t & outWidth, uint32_t & outHeight, ScalingFilter filter = ScalingFilter::Bilinear)
Gets BGRA pixel data with premultiplied alpha for the specified frame, scaled to target dimensions.
Parameters
index The zero-based index of the frame.
targetWidth The desired output width in pixels.
targetHeight The desired output height in pixels.
outWidth Output parameter receiving the actual output width.
outHeight Output parameter receiving the actual output height.
filter The scaling filter to use (Nearest, Bilinear, Bicubic, Lanczos).
Returns
A pointer to BGRA32 premultiplied scaled pixel data, or nullptr on error. The data is cached internally and valid until the next call to this function.
Definition at line 800 of file GifDecoder.cpp.
References GetFramePixelsBGRA32Premultiplied(), GifBolt::GifFrame::height, and GifBolt::GifFrame::width.
Referenced by gb_decoder_get_frame_pixels_bgra32_premultiplied_scaled().
GetHeight()
uint32_t GifBolt::GifDecoder::GetHeight () const
Gets the height of the GIF image.
Returns
The height in pixels, or 0 if no GIF is loaded.
Definition at line 729 of file GifDecoder.cpp.
GetMaxCachedFrames()
uint32_t GifBolt::GifDecoder::GetMaxCachedFrames () const
Gets the maximum number of frames cached in memory.
Returns
The maximum number of cached frames.
Definition at line 762 of file GifDecoder.cpp.
GetMinFrameDelayMs()
uint32_t GifBolt::GifDecoder::GetMinFrameDelayMs () const
Obtient le délai minimal appliqué à chaque frame GIF (en ms).
Returns
Délai minimal en millisecondes.
Definition at line 749 of file GifDecoder.cpp.
GetWidth()
uint32_t GifBolt::GifDecoder::GetWidth () const
Gets the width of the GIF image.
Returns
The width in pixels, or 0 if no GIF is loaded.
Definition at line 724 of file GifDecoder.cpp.
IsLooping()
bool GifBolt::GifDecoder::IsLooping () const
Determines whether the GIF loops indefinitely.
Returns
true if the GIF should loop; false otherwise.
Definition at line 734 of file GifDecoder.cpp.
Referenced by gb_decoder_get_loop_count().
LoadFromFile()
bool GifBolt::GifDecoder::LoadFromFile (const std::string & filePath)
Loads a GIF image from a file path.
Parameters
filePath The file system path to the GIF image.
Returns
true if the GIF was loaded successfully; false otherwise.
Definition at line 689 of file GifDecoder.cpp.
Referenced by gb_decoder_load_from_path().
LoadFromMemory()
bool GifBolt::GifDecoder::LoadFromMemory (const uint8_t * data, size_t length)
Loads a GIF image from an in-memory buffer.
Parameters
data Pointer to the GIF data buffer.
length Length of the buffer in bytes.
Returns
true if the GIF was loaded successfully; false otherwise.
Definition at line 694 of file GifDecoder.cpp.
Referenced by gb_decoder_load_from_memory().
LoadFromUrl()
bool GifBolt::GifDecoder::LoadFromUrl (const std::string & url)
Loads a GIF image from a URL.
Parameters
url The URL to the GIF image.
Returns
true if the GIF was loaded successfully; false otherwise.
Definition at line 699 of file GifDecoder.cpp.
ResetCanvas()
void GifBolt::GifDecoder::ResetCanvas ()
Resets the canvas composition state for looping.
Remarks
Call this when looping back to frame 0 to ensure proper frame composition. This clears the canvas and resets disposal state without reloading the GIF.
Definition at line 1129 of file GifDecoder.cpp.
Referenced by gb_decoder_reset_canvas().
SetCurrentFrame()
void GifBolt::GifDecoder::SetCurrentFrame (uint32_t currentFrame)
Updates the current playback position for prefetch lookahead.
Parameters
currentFrame The current frame being displayed.
Remarks
The prefetch thread uses this to determine which frames to decode next.
Definition at line 1121 of file GifDecoder.cpp.
Referenced by gb_decoder_set_current_frame().
SetMaxCachedFrames()
void GifBolt::GifDecoder::SetMaxCachedFrames (uint32_t maxFrames)
Sets the maximum number of frames to cache in memory.
Parameters
maxFrames Maximum number of frames to keep in the LRU cache. Must be greater than 0.
Definition at line 754 of file GifDecoder.cpp.
Referenced by gb_decoder_set_max_cached_frames().
SetMinFrameDelayMs()
void GifBolt::GifDecoder::SetMinFrameDelayMs (uint32_t minDelayMs)
Définit le délai minimal appliqué à chaque frame GIF (en ms).
Parameters
minDelayMs Délai minimal en millisecondes.
Definition at line 744 of file GifDecoder.cpp.
StartPrefetching()
void GifBolt::GifDecoder::StartPrefetching (uint32_t startFrame)
Starts background prefetching of frames ahead of the current playback position.
Parameters
startFrame The frame to start prefetching from.
Remarks
This starts a background thread that decodes frames ahead of playback, reducing latency for sequential frame access.
Definition at line 1105 of file GifDecoder.cpp.
Referenced by gb_decoder_start_prefetching().
The documentation for this class was generated from the following files:
include/GifDecoder.h
src/GifDecoder.cpp