GifBolt.Native: GifBolt::GifBoltRenderer Class Reference
GifBolt::GifBoltRenderer Class Reference
High-performance GPU-accelerated GIF renderer.
#include <GifBoltRenderer.h>
Public Member Functions
GifBoltRenderer ()
Initializes a new instance of GifBoltRenderer with default context.
GifBoltRenderer (std::shared_ptr< Renderer::IDeviceCommandContext > context)
Initializes a new instance of GifBoltRenderer with a specific device context.
~GifBoltRenderer ()
Destroys the GifBoltRenderer and releases associated resources.
bool Initialize (uint32_t width, uint32_t height)
Initializes the renderer with the specified dimensions.
void SetDeviceContext (std::shared_ptr< Renderer::IDeviceCommandContext > context)
Sets the device context, allowing runtime backend switching.
bool LoadGif (const std::string &path)
Loads a GIF from a file path or URL.
bool LoadGifFromMemory (const uint8_t *data, std::size_t length)
Loads a GIF from an in-memory buffer.
void Play ()
Starts playback of the loaded GIF.
void Stop ()
Stops playback and resets to the first frame.
void Pause ()
Pauses playback at the current frame.
void SetLooping (bool loop)
Sets whether the GIF loops indefinitely.
bool Render ()
Renders the current frame.
void SetCurrentFrame (uint32_t frameIndex)
Sets the current frame index.
uint32_t GetCurrentFrame () const
Gets the current frame index.
uint32_t GetFrameCount () const
Gets the total number of frames in the loaded GIF.
uint32_t GetWidth () const
Gets the width of the GIF image.
uint32_t GetHeight () const
Gets the height of the GIF image.
Detailed Description
High-performance GPU-accelerated GIF renderer.
Provides rendering capabilities with pluggable device backends (DirectX 11, dummy). Handles GIF decoding, frame timing, looping, and GPU-accelerated rendering.
Definition at line 24 of file GifBoltRenderer.h.
Constructor & Destructor Documentation
GifBoltRenderer()
GifBolt::GifBoltRenderer::GifBoltRenderer (std::shared_ptr< Renderer::IDeviceCommandContext > context) explicit
Initializes a new instance of GifBoltRenderer with a specific device context.
Parameters
context The rendering device context to use.
Definition at line 43 of file GifBoltRenderer.cpp.
Member Function Documentation
GetCurrentFrame()
uint32_t GifBolt::GifBoltRenderer::GetCurrentFrame () const
Gets the current frame index.
Returns
The zero-based index of the currently displayed frame.
Definition at line 192 of file GifBoltRenderer.cpp.
GetFrameCount()
uint32_t GifBolt::GifBoltRenderer::GetFrameCount () const
Gets the total number of frames in the loaded GIF.
Returns
The frame count, or 0 if no GIF is loaded.
Definition at line 197 of file GifBoltRenderer.cpp.
GetHeight()
uint32_t GifBolt::GifBoltRenderer::GetHeight () const
Gets the height of the GIF image.
Returns
The height in pixels, or 0 if no GIF is loaded.
Definition at line 207 of file GifBoltRenderer.cpp.
GetWidth()
uint32_t GifBolt::GifBoltRenderer::GetWidth () const
Gets the width of the GIF image.
Returns
The width in pixels, or 0 if no GIF is loaded.
Definition at line 202 of file GifBoltRenderer.cpp.
Initialize()
bool GifBolt::GifBoltRenderer::Initialize (uint32_t width, uint32_t height)
Initializes the renderer with the specified dimensions.
Parameters
width The width of the rendering surface in pixels.
height The height of the rendering surface in pixels.
Returns
true if initialization succeeded; false otherwise.
Definition at line 50 of file GifBoltRenderer.cpp.
Referenced by GifBolt_Initialize().
LoadGif()
bool GifBolt::GifBoltRenderer::LoadGif (const std::string & path)
Loads a GIF from a file path or URL.
Parameters
path The file path or URL to the GIF image.
Returns
true if the GIF was loaded successfully; false otherwise.
Definition at line 63 of file GifBoltRenderer.cpp.
Referenced by GifBolt_LoadGif().
LoadGifFromMemory()
bool GifBolt::GifBoltRenderer::LoadGifFromMemory (const uint8_t * data, std::size_t length)
Loads a GIF from an in-memory buffer.
Parameters
data Pointer to GIF data.
length Length of the data buffer in bytes.
Returns
true if the GIF was loaded successfully; false otherwise.
Definition at line 80 of file GifBoltRenderer.cpp.
Referenced by GifBolt_LoadGifFromMemory().
Render()
bool GifBolt::GifBoltRenderer::Render ()
Renders the current frame.
Returns
true if rendering succeeded; false otherwise.
Definition at line 124 of file GifBoltRenderer.cpp.
Referenced by GifBolt_Render().
SetCurrentFrame()
void GifBolt::GifBoltRenderer::SetCurrentFrame (uint32_t frameIndex)
Sets the current frame index.
Parameters
frameIndex The zero-based index of the frame to display.
Definition at line 184 of file GifBoltRenderer.cpp.
SetDeviceContext()
void GifBolt::GifBoltRenderer::SetDeviceContext (std::shared_ptr< Renderer::IDeviceCommandContext > context)
Sets the device context, allowing runtime backend switching.
Parameters
context The new rendering device context to use.
Definition at line 58 of file GifBoltRenderer.cpp.
SetLooping()
void GifBolt::GifBoltRenderer::SetLooping (bool loop)
Sets whether the GIF loops indefinitely.
Parameters
loop true to enable looping; false for single playback.
Definition at line 119 of file GifBoltRenderer.cpp.
Referenced by GifBolt_SetLooping().
The documentation for this class was generated from the following files:
include/GifBoltRenderer.h
src/GifBoltRenderer.cpp