GifBolt.Native: include/gifbolt_version.h File Reference
gifbolt_version.h File Reference
Version information for GifBolt.Native library.
Macros
#define GIFBOLT_VERSION_MAJOR 1
Major version number (incompatible API changes).
#define GIFBOLT_VERSION_MINOR 0
Minor version number (backwards-compatible functionality added).
#define GIFBOLT_VERSION_PATCH 0
Patch version number (backwards-compatible bug fixes).
#define GIFBOLT_VERSION_STRING "1.0.0"
Full semantic version string (e.g., "1.0.0").
#define GIFBOLT_VERSION_INT (GIFBOLT_VERSION_MAJOR * 10000 + GIFBOLT_VERSION_MINOR * 100 + GIFBOLT_VERSION_PATCH)
Packed integer version (major * 10000 + minor * 100 + patch). Useful for compile-time version checks.
#define GIFBOLT_VERSION_CHECK(major, minor, patch) (GIFBOLT_VERSION_INT >= ((major) * 10000 + (minor) * 100 + (patch)))
Compile-time version comparison macro.
Functions
GB_API int gb_version_get_major (void) noexcept
Gets the major version number at runtime.
GB_API int gb_version_get_minor (void) noexcept
Gets the minor version number at runtime.
GB_API int gb_version_get_patch (void) noexcept
Gets the patch version number at runtime.
GB_API const char * gb_version_get_string (void) noexcept
Gets the full semantic version string at runtime.
GB_API int gb_version_get_int (void) noexcept
Gets the packed integer version at runtime.
GB_API int gb_version_check (int major, int minor, int patch) noexcept
Checks if the runtime version is at least the specified version.
Detailed Description
Version information for GifBolt.Native library.
This header defines version constants and macros for querying the GifBolt.Native library version at compile-time and runtime.
Definition in file gifbolt_version.h.
Macro Definition Documentation
GIFBOLT_VERSION_CHECK
#define GIFBOLT_VERSION_CHECK (major, minor, patch) (GIFBOLT_VERSION_INT >= ((major) * 10000 + (minor) * 100 + (patch)))
Compile-time version comparison macro.
Parameters
major Major version to check against.
minor Minor version to check against.
patch Patch version to check against.
Returns
1 if current version >= specified version; 0 otherwise.
Definition at line 45 of file gifbolt_version.h.
Function Documentation
gb_version_check()
GB_API int gb_version_check (int major, int minor, int patch) noexcept
Checks if the runtime version is at least the specified version.
Parameters
major Minimum required major version.
minor Minimum required minor version.
patch Minimum required patch version.
Returns
1 if runtime version >= specified version; 0 otherwise.
Definition at line 33 of file gifbolt_version.cpp.
References gb_version_check(), and GIFBOLT_VERSION_INT.
Referenced by gb_version_check().
gb_version_get_int()
GB_API int gb_version_get_int (void) noexcept
Gets the packed integer version at runtime.
Returns
The version as an integer (major * 10000 + minor * 100 + patch).
Definition at line 28 of file gifbolt_version.cpp.
References gb_version_get_int(), and GIFBOLT_VERSION_INT.
Referenced by gb_version_get_int().
gb_version_get_major()
GB_API int gb_version_get_major (void) noexcept
Gets the major version number at runtime.
Returns
The major version number.
Definition at line 8 of file gifbolt_version.cpp.
References gb_version_get_major(), and GIFBOLT_VERSION_MAJOR.
Referenced by gb_version_get_major().
gb_version_get_minor()
GB_API int gb_version_get_minor (void) noexcept
Gets the minor version number at runtime.
Returns
The minor version number.
Definition at line 13 of file gifbolt_version.cpp.
References gb_version_get_minor(), and GIFBOLT_VERSION_MINOR.
Referenced by gb_version_get_minor().
gb_version_get_patch()
GB_API int gb_version_get_patch (void) noexcept
Gets the patch version number at runtime.
Returns
The patch version number.
Definition at line 18 of file gifbolt_version.cpp.
References gb_version_get_patch(), and GIFBOLT_VERSION_PATCH.
Referenced by gb_version_get_patch().
gb_version_get_string()
GB_API const char * gb_version_get_string (void) noexcept
Gets the full semantic version string at runtime.
Returns
A null-terminated version string (e.g., "1.0.0"). The string is statically allocated and must not be freed.
Definition at line 23 of file gifbolt_version.cpp.
References gb_version_get_string(), and GIFBOLT_VERSION_STRING.
Referenced by gb_version_get_string().