GifBolt.Native: GIF Renderer Functions
GIF Renderer Functions
Functions
GB_API gb_renderer_t GifBolt_Create (void)
Creates a new GIF renderer instance.
GB_API void GifBolt_Destroy (gb_renderer_t renderer)
Destroys a GIF renderer instance and releases resources.
GB_API int GifBolt_Initialize (gb_renderer_t renderer, unsigned int width, unsigned int height)
Initializes the renderer with the specified dimensions.
GB_API int GifBolt_LoadGif (gb_renderer_t renderer, const char *path)
Loads a GIF from the specified file path.
GB_API int GifBolt_LoadGifFromMemory (gb_renderer_t renderer, const void *data, int length)
Loads a GIF from an in-memory buffer.
GB_API void GifBolt_Play (gb_renderer_t renderer)
Starts playback of the loaded GIF.
GB_API void GifBolt_Pause (gb_renderer_t renderer)
Pauses playback of the GIF.
GB_API void GifBolt_Stop (gb_renderer_t renderer)
Stops playback and resets to the first frame.
GB_API void GifBolt_SetLooping (gb_renderer_t renderer, int loop)
Sets the looping behavior of the GIF.
GB_API int GifBolt_Render (gb_renderer_t renderer)
Renders the current frame.
GB_API void gb_decoder_set_max_cached_frames (gb_decoder_t decoder, unsigned int maxFrames)
Sets the maximum number of frames to cache in memory.
GB_API unsigned int gb_decoder_get_max_cached_frames (gb_decoder_t decoder)
Gets the maximum number of frames cached in memory.
GB_API const void * gb_decoder_get_frame_pixels_bgra32_premultiplied_scaled (gb_decoder_t decoder, int index, int targetWidth, int targetHeight, int *outWidth, int *outHeight, int *byteCount, int filterType)
Gets BGRA32 pixel data with premultiplied alpha for the specified frame, scaled to target dimensions.
GB_API void gb_decoder_start_prefetching (gb_decoder_t decoder, int startFrame)
Starts background prefetching of frames ahead of the current playback position.
GB_API void gb_decoder_stop_prefetching (gb_decoder_t decoder)
Stops background prefetching and joins the prefetch thread.
GB_API void gb_decoder_set_current_frame (gb_decoder_t decoder, int currentFrame)
Updates the current playback position for prefetch lookahead.
GB_API void gb_decoder_reset_canvas (gb_decoder_t decoder)
Resets the canvas composition state for looping.
Detailed Description
Function Documentation
gb_decoder_get_frame_pixels_bgra32_premultiplied_scaled()
GB_API const void * gb_decoder_get_frame_pixels_bgra32_premultiplied_scaled (gb_decoder_t decoder, int index, int targetWidth, int targetHeight, int * outWidth, int * outHeight, int * byteCount, int filterType)
Gets BGRA32 pixel data with premultiplied alpha for the specified frame, scaled to target dimensions.
Parameters
decoder The decoder handle.
index The zero-based frame index.
targetWidth The desired output width in pixels.
targetHeight The desired output height in pixels.
[out] outWidth Pointer to receive the actual output width.
[out] outHeight Pointer to receive the actual output height.
[out] byteCount Pointer to receive the size of pixel data in bytes.
filterType The scaling filter to use (0=Nearest, 1=Bilinear, 2=Bicubic, 3=Lanczos).
Returns
Pointer to BGRA32 premultiplied scaled pixel data, or NULL on error. The pointer is valid until the next decoder operation.
Definition at line 232 of file gifbolt_c.cpp.
References GifBolt::GifDecoder::GetFramePixelsBGRA32PremultipliedScaled().
gb_decoder_get_max_cached_frames()
GB_API unsigned int gb_decoder_get_max_cached_frames (gb_decoder_t decoder)
Gets the maximum number of frames cached in memory.
Parameters
decoder The decoder handle.
Returns
The maximum number of cached frames, or 0 on error.
Definition at line 44 of file gifbolt_c.cpp.
gb_decoder_reset_canvas()
GB_API void gb_decoder_reset_canvas (gb_decoder_t decoder)
Resets the canvas composition state for looping.
Parameters
decoder The decoder handle.
Remarks
Call this when looping back to frame 0 to ensure proper frame composition.
Definition at line 332 of file gifbolt_c.cpp.
References GifBolt::GifDecoder::ResetCanvas().
gb_decoder_set_current_frame()
GB_API void gb_decoder_set_current_frame (gb_decoder_t decoder, int currentFrame)
Updates the current playback position for prefetch lookahead.
Parameters
decoder The decoder handle.
currentFrame The current frame being displayed.
Remarks
The prefetch thread uses this to determine which frames to decode next.
Definition at line 322 of file gifbolt_c.cpp.
References GifBolt::GifDecoder::SetCurrentFrame().
gb_decoder_set_max_cached_frames()
GB_API void gb_decoder_set_max_cached_frames (gb_decoder_t decoder, unsigned int maxFrames)
Sets the maximum number of frames to cache in memory.
Parameters
decoder The decoder handle.
maxFrames Maximum number of frames to keep in the LRU cache (must be > 0).
Definition at line 34 of file gifbolt_c.cpp.
References GifBolt::GifDecoder::SetMaxCachedFrames().
gb_decoder_start_prefetching()
GB_API void gb_decoder_start_prefetching (gb_decoder_t decoder, int startFrame)
Starts background prefetching of frames ahead of the current playback position.
Parameters
decoder The decoder handle.
startFrame The frame to start prefetching from.
Remarks
This starts a background thread that decodes frames ahead of playback, reducing latency for sequential frame access.
Definition at line 302 of file gifbolt_c.cpp.
References GifBolt::GifDecoder::StartPrefetching().
gb_decoder_stop_prefetching()
GB_API void gb_decoder_stop_prefetching (gb_decoder_t decoder)
Stops background prefetching and joins the prefetch thread.
Parameters
decoder The decoder handle.
Definition at line 312 of file gifbolt_c.cpp.
References GifBolt::GifDecoder::StopPrefetching().
GifBolt_Create()
GB_API gb_renderer_t GifBolt_Create (void)
Creates a new GIF renderer instance.
Returns
A handle to the renderer, or NULL if creation fails.
Definition at line 343 of file gifbolt_c.cpp.
GifBolt_Destroy()
GB_API void GifBolt_Destroy (gb_renderer_t renderer)
Destroys a GIF renderer instance and releases resources.
Parameters
renderer The renderer handle to destroy (can be NULL).
Definition at line 355 of file gifbolt_c.cpp.
GifBolt_Initialize()
GB_API int GifBolt_Initialize (gb_renderer_t renderer, unsigned int width, unsigned int height)
Initializes the renderer with the specified dimensions.
Parameters
renderer The renderer handle.
width The rendering surface width in pixels.
height The rendering surface height in pixels.
Returns
1 if successful; 0 otherwise.
Definition at line 365 of file gifbolt_c.cpp.
References GifBolt::GifBoltRenderer::Initialize().
GifBolt_LoadGif()
GB_API int GifBolt_LoadGif (gb_renderer_t renderer, const char * path)
Loads a GIF from the specified file path.
Parameters
renderer The renderer handle.
path The file path to the GIF image.
Returns
1 if successful; 0 otherwise.
Definition at line 375 of file gifbolt_c.cpp.
References GifBolt::GifBoltRenderer::LoadGif().
GifBolt_LoadGifFromMemory()
GB_API int GifBolt_LoadGifFromMemory (gb_renderer_t renderer, const void * data, int length)
Loads a GIF from an in-memory buffer.
Parameters
renderer The renderer handle.
data Pointer to the GIF data buffer.
length Length of the buffer in bytes.
Returns
1 if successful; 0 otherwise.
Definition at line 385 of file gifbolt_c.cpp.
References GifBolt::GifBoltRenderer::LoadGifFromMemory().
GifBolt_Pause()
GB_API void GifBolt_Pause (gb_renderer_t renderer)
Pauses playback of the GIF.
Parameters
renderer The renderer handle.
Definition at line 407 of file gifbolt_c.cpp.
References GifBolt::GifBoltRenderer::Pause().
GifBolt_Play()
GB_API void GifBolt_Play (gb_renderer_t renderer)
Starts playback of the loaded GIF.
Parameters
renderer The renderer handle.
Definition at line 397 of file gifbolt_c.cpp.
References GifBolt::GifBoltRenderer::Play().
GifBolt_Render()
GB_API int GifBolt_Render (gb_renderer_t renderer)
Renders the current frame.
Parameters
renderer The renderer handle.
Returns
1 if rendering succeeded; 0 otherwise.
Definition at line 437 of file gifbolt_c.cpp.
References GifBolt::GifBoltRenderer::Render().
GifBolt_SetLooping()
GB_API void GifBolt_SetLooping (gb_renderer_t renderer, int loop)
Sets the looping behavior of the GIF.
Parameters
renderer The renderer handle.
loop 1 to enable looping; 0 to disable.
Definition at line 427 of file gifbolt_c.cpp.
References GifBolt::GifBoltRenderer::SetLooping().
GifBolt_Stop()
GB_API void GifBolt_Stop (gb_renderer_t renderer)
Stops playback and resets to the first frame.
Parameters
renderer The renderer handle.
Definition at line 417 of file gifbolt_c.cpp.
References GifBolt::GifBoltRenderer::Stop().