GifBolt.Native: GIF Decoder Functions
GIF Decoder Functions
Functions
GB_API gb_decoder_t gb_decoder_create (void)
Creates a new GIF decoder instance.
GB_API void gb_decoder_destroy (gb_decoder_t decoder)
Destroys a GIF decoder instance and releases resources.
GB_API int gb_decoder_load_from_path (gb_decoder_t decoder, const char *path)
Loads a GIF from the specified file path.
GB_API int gb_decoder_load_from_memory (gb_decoder_t decoder, const void *data, int length)
Loads a GIF from an in-memory buffer.
GB_API int gb_decoder_get_frame_count (gb_decoder_t decoder)
Gets the total number of frames in the loaded GIF.
GB_API int gb_decoder_get_width (gb_decoder_t decoder)
Gets the width of the GIF image.
GB_API int gb_decoder_get_height (gb_decoder_t decoder)
Gets the height of the GIF image.
GB_API int gb_decoder_get_loop_count (gb_decoder_t decoder)
Gets the looping behavior of the GIF.
GB_API int gb_decoder_get_frame_delay_ms (gb_decoder_t decoder, int index)
Gets the display duration of the specified frame.
GB_API const void * gb_decoder_get_frame_pixels_rgba32 (gb_decoder_t decoder, int index, int *byteCount)
Gets the RGBA32 pixel data for the specified frame.
GB_API const void * gb_decoder_get_frame_pixels_bgra32_premultiplied (gb_decoder_t decoder, int index, int *byteCount)
Gets BGRA32 pixel data with premultiplied alpha for the specified frame.
GB_API unsigned int gb_decoder_get_background_color (gb_decoder_t decoder)
Gets the background color of the GIF.
Detailed Description
Function Documentation
gb_decoder_create()
GB_API gb_decoder_t gb_decoder_create (void)
Creates a new GIF decoder instance.
Returns
A handle to the decoder, or NULL if creation fails.
Definition at line 54 of file gifbolt_c.cpp.
gb_decoder_destroy()
GB_API void gb_decoder_destroy (gb_decoder_t decoder)
Destroys a GIF decoder instance and releases resources.
Parameters
decoder The decoder handle to destroy (can be NULL).
Definition at line 66 of file gifbolt_c.cpp.
gb_decoder_get_background_color()
GB_API unsigned int gb_decoder_get_background_color (gb_decoder_t decoder)
Gets the background color of the GIF.
Parameters
decoder The decoder handle.
Returns
The background color as RGBA32 (0xAABBGGRR), or 0xFF000000 (black) on error.
Definition at line 292 of file gifbolt_c.cpp.
References GifBolt::GifDecoder::GetBackgroundColor().
gb_decoder_get_frame_count()
GB_API int gb_decoder_get_frame_count (gb_decoder_t decoder)
Gets the total number of frames in the loaded GIF.
Parameters
decoder The decoder handle.
Returns
The frame count, or 0 if no GIF is loaded or on error.
Definition at line 98 of file gifbolt_c.cpp.
gb_decoder_get_frame_delay_ms()
GB_API int gb_decoder_get_frame_delay_ms (gb_decoder_t decoder, int index)
Gets the display duration of the specified frame.
Parameters
decoder The decoder handle.
index The zero-based frame index.
Returns
The frame delay in milliseconds, or 0 on error.
Definition at line 139 of file gifbolt_c.cpp.
References GifBolt::GifFrame::delayMs.
gb_decoder_get_frame_pixels_bgra32_premultiplied()
GB_API const void * gb_decoder_get_frame_pixels_bgra32_premultiplied (gb_decoder_t decoder, int index, int * byteCount)
Gets BGRA32 pixel data with premultiplied alpha for the specified frame.
Parameters
decoder The decoder handle.
index The zero-based frame index.
[out] byteCount Pointer to receive the size of pixel data in bytes.
Returns
Pointer to BGRA32 premultiplied pixel data, or NULL on error. The pointer is valid until the next decoder operation. This is optimized for Avalonia and other frameworks requiring premultiplied alpha.
Definition at line 193 of file gifbolt_c.cpp.
References GifBolt::GifDecoder::GetFramePixelsBGRA32Premultiplied(), and GifBolt::GifFrame::pixels.
gb_decoder_get_frame_pixels_rgba32()
GB_API const void * gb_decoder_get_frame_pixels_rgba32 (gb_decoder_t decoder, int index, int * byteCount)
Gets the RGBA32 pixel data for the specified frame.
Parameters
decoder The decoder handle.
index The zero-based frame index.
[out] byteCount Pointer to receive the size of pixel data in bytes.
Returns
Pointer to RGBA32 pixel data, or NULL on error. The pointer is valid until the next decoder operation.
Definition at line 161 of file gifbolt_c.cpp.
References GifBolt::GifFrame::pixels.
gb_decoder_get_height()
GB_API int gb_decoder_get_height (gb_decoder_t decoder)
Gets the height of the GIF image.
Parameters
decoder The decoder handle.
Returns
The height in pixels, or 0 if no GIF is loaded or on error.
Definition at line 118 of file gifbolt_c.cpp.
gb_decoder_get_loop_count()
GB_API int gb_decoder_get_loop_count (gb_decoder_t decoder)
Gets the looping behavior of the GIF.
Parameters
decoder The decoder handle.
Returns
-1 if the GIF loops indefinitely (or loop count is unknown), 0 if the GIF does not loop, or positive value for specific loop count.
Definition at line 128 of file gifbolt_c.cpp.
References GifBolt::GifDecoder::IsLooping().
gb_decoder_get_width()
GB_API int gb_decoder_get_width (gb_decoder_t decoder)
Gets the width of the GIF image.
Parameters
decoder The decoder handle.
Returns
The width in pixels, or 0 if no GIF is loaded or on error.
Definition at line 108 of file gifbolt_c.cpp.
gb_decoder_load_from_memory()
GB_API int gb_decoder_load_from_memory (gb_decoder_t decoder, const void * data, int length)
Loads a GIF from an in-memory buffer.
Parameters
decoder The decoder handle.
data Pointer to the GIF data buffer.
length Length of the buffer in bytes.
Returns
1 if successful; 0 otherwise.
Definition at line 86 of file gifbolt_c.cpp.
References GifBolt::GifDecoder::LoadFromMemory().
gb_decoder_load_from_path()
GB_API int gb_decoder_load_from_path (gb_decoder_t decoder, const char * path)
Loads a GIF from the specified file path.
Parameters
decoder The decoder handle.
path The file path to the GIF image.
Returns
1 if successful; 0 otherwise.
Definition at line 76 of file gifbolt_c.cpp.
References GifBolt::GifDecoder::LoadFromFile().